# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

""" This file holds defintions of custom constraints and their vaules related to version
"""

# --------------------------------------------------------------------------------
# OS version constraint settings definitions and their values
# --------------------------------------------------------------------------------
constraint_setting(name = "os_version")

constraint_value(
    name = "qnx_7_1_0",
    constraint_setting = ":os_version",
)

constraint_value(
    name = "qnx_8_0_0",
    constraint_setting = ":os_version",
)

constraint_value(
    name = "qnx_8_1_0",
    constraint_setting = ":os_version",
)

constraint_value(
    name = "qnx_8_2_0",
    constraint_setting = ":os_version",
)

# --------------------------------------------------------------------------------
# GCC version constraint settings definitions and their values
# --------------------------------------------------------------------------------
constraint_setting(name = "gcc_version")

constraint_value(
    name = "gcc_12_2_0",
    constraint_setting = ":gcc_version",
)

constraint_value(
    name = "gcc_8_3_0",
    constraint_setting = ":gcc_version",
)

