# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

""" This file holds defintions of custom constraints and their vaules related to runtime ecosystem
    Examples: autosd, android_auto, adaptive_autosar ...
""" 

# --------------------------------------------------------------------------------
# OS version constraint settings definitions and their values
# --------------------------------------------------------------------------------
constraint_setting(name="runtime_ecosystem")

constraint_value(
    name = "autosd",
    constraint_setting = ":runtime_ecosystem",
)

constraint_value(
    name = "posix",
    constraint_setting = ":runtime_ecosystem",
)
