# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

package(default_visibility = ["//visibility:public"])

config_setting(
    name = "aarch64-linux",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:linux",
    ],
)

config_setting(
    name = "aarch64-qnx",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:qnx",
    ],
)

config_setting(
    name = "aarch64-qnx7",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:qnx",
        "@score_bazel_platforms//version:sdp_7.1.0",
    ],
)

config_setting(
    name = "aarch64-qnx8",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:qnx",
        "@score_bazel_platforms//version:sdp_8.0.0",
    ],
)

config_setting(
    name = "x86_64-linux",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)

config_setting(
    name = "x86_64-qnx",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:qnx",
    ],
)

config_setting(
    name = "x86_64-qnx7",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:qnx",
        "@score_bazel_platforms//version:sdp_7.1.0",
    ],
)

config_setting(
    name = "x86_64-qnx8",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:qnx",
        "@score_bazel_platforms//version:sdp_8.0.0",
    ],
)
